### ISSUE TITLE
Building from master

### ISSUE THREAD

**Issue by anamba** [nerves-web-kiosk/kiosk_system_rpi4#3]
### Environment

* Elixir version (`elixir -v`):
Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.10.2 (compiled with Erlang/OTP 22)

* Nerves environment: (`mix nerves.env --info`)
|nerves_bootstrap| Environment Package List

  No packages found
|nerves_bootstrap| Loadpaths Start

Nerves environment
  MIX_TARGET:   host
  MIX_ENV:      dev

NERVES_SYSTEM is unset
NERVES_TOOLCHAIN is unset
|nerves_bootstrap| Environment Variable List
  target:     host
  toolchain:  unset
  system:     unset
  app:        /Users/anamba/Sites/elixir/hello_nerves

|nerves_bootstrap| Loadpaths End

* Additional information about your host, target hardware or environment that
  may help
Hard to know what would be helpful. I use macOS and Ubuntu.

Despite mentions of 1.8.1 and 1.8.2 releases in the history, there are no releases on hex.pm, so I tried to run what's currently on master. I am new to Nerves (as in, I am trying it today for the first time), so that turned out not to be as straightforward as I expected.

I kept getting an error following "Resolving Nerves artifacts..." because it was trying to download files for this project from the official nerves-project releases, which naturally would be 404. I finally found where the URL was coming from (artifact_sites in mix.exs), but correcting the URL wouldn't have fixed the issue though, as this project doesn't have any release artifacts...

Eventually I figured out I could just comment out artifact_sites entirely. Is that the way to go for now? That got `mix deps.get` to work and `mix firmware` appears to be building something, but wow, it's not kidding when it says:
```
|Elixir.Docker| Starting Build... (this may take a while)
```

**Comment by anamba** [comment]
In the end, after hours of building, it 404'd on qtwebengine-everywhere-src-5.13.0.tar.xz and failed. Any ideas on next steps? My goal is to create a QR code reader with a web-based UI. I have a rpi4 with camera.

**Comment by simpers** [comment]
I have been trying to get this image working lately and it seems I can't get it working on either my Mac or my Arch laptop.

Could somebody post their environment and package versions where it works so I can try to mimic that or find some changelogs to do some debugging?

**Comment by fhunleth** [comment]
This project is being brought back from the dead, so closing old issues since everything has changed since 2020.
